# Site settings
title: mich312 Blog
email: michael.steurer[at]me.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog about tech, design and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mich312.com" # the base hostname & protocol for your site
twitter_username: mich312_
github_username: mich312

# Build settings
markdown: kramdown
